import React from 'react';

const AboutCT = () => {
    return (
        <div style={containerStyle}>
            <div style={contentStyle}>
                <div style={sectionStyle}>
                    <h2 style={headerStyle}>About Our Platform</h2>
                    <p>Welcome to our platform, a dynamic and interactive space designed to revolutionize the way quizzes are created, shared, and enjoyed. Our platform draws inspiration from popular quiz-hosting services like Kahoot!, providing educators and learners with a powerful toolset to facilitate engaging learning experiences.</p>
                </div>
                <div style={sectionStyle}>
                    <h2 style={headerStyle}>Mission Statement</h2>
                    <p>Our mission is to empower educators to create customized quizzes tailored to their unique teaching objectives, while providing students with a fun and effective way to reinforce their learning through interactive quizzes.</p>
                </div>
                <div style={sectionStyle}>
                    <h2 style={headerStyle}>Key Features</h2>
                    <ul>
                        <li><strong>User-Friendly Interface:</strong> Our platform boasts a user-friendly interface that makes creating, accessing, and participating in quizzes a breeze. Whether you're a seasoned educator or a student eager to test your knowledge, our intuitive design ensures a seamless experience for all users.</li>
                        <li><strong>Create Quiz Page:</strong> Educators can unleash their creativity on our "Create Quiz" page, where they can craft quizzes tailored to their curriculum, subject matter, and learning objectives. With support for multiple question types, customizable time limits, and more, the possibilities are endless.</li>
                        <li><strong>Library Page:</strong> The "Library" page serves as a centralized hub where educators can store and organize their created quizzes for easy access. Gone are the days of sifting through countless files and folders—our platform streamlines the quiz management process, allowing educators to focus on what they do best: teaching.</li>
                        <li><strong>Join Page:</strong> Students eagerly await the opportunity to put their knowledge to the test on our "Join" page. By entering the unique pin code generated by the quiz host, students can join live quizzes in real time, immersing themselves in a collaborative learning environment.</li>
                        <li><strong>Point System and Token Shop:</strong> Our platform rewards student engagement and achievement through a comprehensive point system. Correctly answered questions earn students points, with top performers earning tokens redeemable at our exclusive Token Shop. By incentivizing participation and excellence, we motivate students to strive for success.</li>
                    </ul>
                </div>
                <div style={sectionStyle}>
                    <h2 style={headerStyle}>Conclusion</h2>
                    <p>Our platform represents the future of interactive learning, where educators and students come together to explore, engage, and excel. Join us on this exciting journey as we revolutionize the way quizzes are experienced and enjoyed.</p>
                </div>
            </div>
        </div>
    );
};

const containerStyle = {
    width: '80%', // 4/5th of the screen
    margin: '0 auto', // Center horizontally
};

const contentStyle = {
    textAlign: 'left',
};

const sectionStyle = {
    marginBottom: '30px',
};

const headerStyle = {
    fontSize: '24px',
    fontWeight: 'bold',
    marginBottom: '15px',
};

export default AboutCT;
